name: 'Test'

on:
  push:
  schedule: # Keep the cache alive!
    - cron: 7 1 * * fri

jobs:
  test:
    name: ${{ matrix.os }} ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        version: [ "v3.3-stable", "v3.3.4-stable", "v3.4-stable" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
      - name: Install npx
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: npm i -g npx
      - name: Start HTTP server
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: npx http-server --port=7121 ./test/integration/streaming/ &
      - name: Setup Godot
        id: setup-godot
        uses: lihop/setup-godot@v0.1.0
        with:
          version: ${{ matrix.version }}
      - name: Install plugins
        shell: bash
        run: godot --no-window -s plug.gd install
      - name: Import files
        shell: bash
        run: godot --editor --quit
      - name: Run tests
        shell: bash
        run: godot --no-window -s addons/gut/gut_cmdln.gd -gconfig=.gutconfig_all.json
